### PR TITLE
prevent autoclosing from triggering inside attributes, solves #2

### PR DESCRIPTION
**Pull request by marcofugaro**
Works both for html attributes and JSX props

### CODE REVIEW

**Comment by marcofugaro** [comment]
@MiracleBlue dude, you made a fork because the original package was unmaintained, and now you don't maintain this package?

Please approve this PR before I do a fork of your fork.

**Comment by MiracleBlue** [comment]
My bad, I didn't spot the notification. Thanks for the pr!

**Comment by MiracleBlue** [comment]
I'll publish it in the next day or so to the package repo

**Comment by MiracleBlue** [comment]
Added you as collaborator if you ever want to merge your own PRs, and looks like I've missed 4 other reported issues! I have no idea how it only now sends me an email, maybe my email settings are bad :(

**Comment by marcofugaro** [comment]
😄  thanks dude!

**Comment by MiracleBlue** [comment]
You're a genius, that PR fixes everything!  I've published the new version 0.2.2 :)

Thanks so much!

**Comment by marcofugaro** [comment]
LOL, nice to hear 😆  glad I could help!

**Pull request merged**
